clinic/urls.py
from django.urls import include, path

from .views import clinic, students, teachers, researcher, Plotting_Two_Variables, tables, maps_loc, patient, physician
from django.views.generic.base import TemplateView
#from .views import graph, play_count_by_month

urlpatterns = [
    path('', clinic.home, name='home'),
    path('Plotting-Two-Variables', Plotting_Two_Variables.chart, name='chart'),
    path('maps_loc', maps_loc.chart, name='chart'),
    path('tables', tables.table, name='table'),
    path('hello', maps_loc.hello, name='hello'),


    path('patient/', include(([
        #path('', DataListView.as_view(), name='data_list'),
        path('', patient.QuizListView.as_view(), name='quiz_list'),
        #path('interests/', students.StudentInterestsView.as_view(), name='student_interests'),
    ], 'clinic'), namespace='patient')),

    path('students/', include(([
        #path('', DataListView.as_view(), name='data_list'),
        path('', students.QuizListView.as_view(), name='quiz_list'),

        #path('interests/', students.StudentInterestsView.as_view(), name='student_interests'),
        path('taken/', students.TakenQuizListView.as_view(), name='taken_quiz_list'),
        path('quiz/<int:pk>/', students.take_quiz, name='take_quiz'),
    ], 'clinic'), namespace='students')),


    path('teachers/', include(([
        path('', teachers.DataListView.as_view(), name='data_change_list'),
        path('spiral_list', teachers.spiralView.as_view(), name='spiral_list'),
        path('data/<int:pk>/', teachers.DataUpdateView.as_view(), name='data_change'),
        path('data/add/', teachers.DataCreateView.as_view(), name='data_add'),
    ], 'clinic'), namespace='teachers')),

    path('physician/', include(([
        path('', physician.DataListView.as_view(), name='data_change_list'),
        path('spiral_list', physician.spiralView.as_view(), name='spiral_list'),
        path('data/<int:pk>/', physician.DataUpdateView.as_view(), name='data_change'),
        path('data/add/', physician.DataCreateView.as_view(), name='data_add'),
    ], 'clinic'), namespace='teachers')),

    path('researcher/', include(([
        #path('patient_data1', TemplateView.as_view(template_name = 'patient/patient_data1.html'), name = 'patient_data1'),
        #path('graph', TemplateView.as_view(template_name = 'clinic/researcher/graph.html'), name='graph'),
        #path('api/play_count_by_month', researcher.play_count_by_month.views, name='play_count_by_month'),
        path('', researcher.DataListView.as_view(), name='data_list'),
        #path('graph/', researcher.GraphView.as_view(), name='graph_list')
    ], 'clinic'), namespace='researcher')),


]

clinic/views/researcher.py
from django.contrib.auth import login
from django.shortcuts import redirect
from django.views.generic import CreateView
from django.views.generic import ListView
from django.urls import include, path
from django.shortcuts import render
from ..forms import ResearcherSignUpForm
from ..models import User, Data, Play
from django.shortcuts import render
from django.db import connections
from django.db.models import Count
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import TemplateView



class ResearcherSignUpView(CreateView):
    model = User
    form_class = ResearcherSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'researcher'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user,backend='django.contrib.auth.backends.ModelBackend')
        return redirect('researcher:data_list')

class DataListView(ListView):
    model = Data
    ordering = ('name', )
    #context_object_name = 'qjuizzes'
    template_name = 'clinic/researcher/data_list.html'

clinic/templates/researcher/charts_list.html
{% extends 'base.html' %}
{% block js %}
{% if user.is_authenticated %}
{% load loads_extra %}
{% load static %}

<br>
<p>Logged in user: {{ user.username }}</p>
<br>
<table id="example" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">
            <thead>
            <tr>
              <th>SUP:</th>
              <th>Item N.:</th>
              <th>SKU</th>
              <th>Description</th>
              <th>6mBack</th>
              <th>5mBack</th>
              <th>4mBack</th>
              <th>3mBack</th>
              <th>2mBack</th>
              <th>Lmonth</th>
              <th>CMonth</th>
              <th>Nmonth</th>
              <th>N2Month</th>
              <th>N3month</th>
              <th>AVGrowth</th>
              <th></th>
              <!-- This is header for new button to draw the Bar Charts -->
              <th></th>

            </tr>
            </thead>
            <tbody>
              {% for records in sorted %}
                <tr>
                <td>{{ records.sup }}</td>
                <td>{{ records.item_n }}</td>
                <td>{{ records.sku }}</td>
                <td>{{ records.description }}</td>
                <td>{{ records.sales6m }}</td>
                <td>{{ records.sales5m }}</td>
                <td>{{ records.sales4m }}</td>
                <td>{{ records.sales3m }}</td>
                <td>{{ records.sales2m }}</td>
                <td>{{ records.saleslm }}</td>
                <td>{{ records.sales_this_month }}</td>
                <td>{{ records.m1predicted }}</td>
                <td>{{ records.m2predicted }}</td>
                <td>{{ records.m3predicted }}</td>
                <td>{{ records.avgrowths }}</td>

                <td>
                  <a href="{% url 'edit' records.id %}" class="btn btn-secondary">Edit</a>
                </td>
                <!-- Add new button for drawing Bar Charts -->
                <td>
                  <button class="btn btn-secondary" onclick="draw_chart(this)" data-toggle="modal" data-target="#myModal">Chart</button>
                </td>

            </tr>
          {% endfor %}

         </tbody>
        </table>
        <!-- Modal which Bar Chart will be placed -->
          <div id="myModal" class="modal fade" role="dialog">
              <div class="modal-dialog" style="max-width: 900px !important">
              <!-- Modal content-->
                  <div class="modal-content">
                      <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal">&times;</button>
                      </div>
                      <div class="modal-body">
                          <!-- <svg> element which will contains the Bar Chart -->
                          <svg width="1000" height="500"></svg>
                      </div>
                      <div class="modal-footer">
                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                      </div>
                  </div>
              </div>
          </div>
          <!-- Insert D3.js Library -->
          <script src="https://d3js.org/d3.v5.min.js"></script>
          <script>
          $(document).ready(function() {
              var table = $('#example').DataTable( {
              fixedColumns: true,
                  lengthChange: true,
                  buttons: [ 'copy', 'excel', 'csv', 'pdf', 'colvis' ]
              } );

              table.buttons().container()
                  .appendTo( '#example_wrapper .col-md-6:eq(0)' );
          } );
          // Main functions for Drawing Bar chart using D3.js
          function draw_chart(item){
              // `item` is the current clicked button element
              // `row_ele` is the parent <tr> element of the current clicked button element
              row_ele = item.closest('tr');
              // Get the value from the <td> element using nth-child()
              val_6mBack = row_ele.querySelector("td:nth-child(5)");
              val_5mBack = row_ele.querySelector("td:nth-child(6)");
              val_4mBack = row_ele.querySelector("td:nth-child(7)");
              val_3mBack = row_ele.querySelector("td:nth-child(8)");
              val_2mBack = row_ele.querySelector("td:nth-child(9)");
              val_Lmonth = row_ele.querySelector("td:nth-child(10)");
              val_CMonth = row_ele.querySelector("td:nth-child(11)");
              val_Nmonth = row_ele.querySelector("td:nth-child(12)");
              val_N2Month = row_ele.querySelector("td:nth-child(13)");
              val_N3month = row_ele.querySelector("td:nth-child(14)");

              // `data` is variable which store the data for Bar Charts
              data = []
              // Pushing data as key/value type objects into the `data` variable
              data.push({'label':'6mBack', 'value': val_6mBack.innerHTML})
              data.push({'label':'5mBack', 'value': val_5mBack.innerHTML})
              data.push({'label':'4mBack', 'value': val_4mBack.innerHTML})
              data.push({'label':'3mBack', 'value': val_3mBack.innerHTML})
              data.push({'label':'2mBack', 'value': val_2mBack.innerHTML})
              data.push({'label':'Lmonth', 'value': val_Lmonth.innerHTML})
              data.push({'label':'CMonth', 'value': val_CMonth.innerHTML})
              data.push({'label':'Nmonth', 'value': val_Nmonth.innerHTML})
              data.push({'label':'N2Month', 'value': val_N2Month.innerHTML})
              data.push({'label':'N3month', 'value': val_N3month.innerHTML})


              // Set <svg> element's width and height
              var svg = d3.select("svg"),
                          margin = 200,
                          width = svg.attr("width") - margin,
                          height = svg.attr("height") - margin
              // Remove the old contents of the <svg> element
              svg.selectAll('*').remove()
              // Initialize X-axis and Y-axis for Bar Chart
              var xScale = d3.scaleBand().range([0, width]).padding(0.4),
                  yScale = d3.scaleLinear().range([height, 0]);

              // Set all group which is placed in the <svg>element
              // transform to (50,100) on <svg> area , margint in svg has been changed to 300 and instead 50/100, changed to 100/300, but then back.
              var g = svg.append("g")
                          .attr("transform", "translate(" + 50 + "," + 100 + ")");


              xScale.domain(data.map(function(d) { return d.label; }));
              // If all values of data will be zero, we will fix the range of the Y-axis
              if(d3.max(data, function(d) { return d.value; }) == 0){
                  yScale.domain([0, 10]);
              }else{
                  // If all is not zero, we will set Y-axis from 0 to maximum value.
                  yScale.domain([0, d3.max(data, function(d) { return Number(d.value); })]);
              }

              // Set X- axis
              g.append("g")
               .attr("transform", "translate(0," + height + ")")
               .call(d3.axisBottom(xScale));
               // Set Y-axis using ticket
              g.append("g")
               .call(d3.axisLeft(yScale).tickFormat(function(d){
                   return d;
               }).ticks(10));

               console.log(data)
              // Draw Bar Chart using <rect> element by data which is stored in the `data` variable
              g.selectAll(".bar")
               .data(data)
               .enter().append("rect")
               .attr("class", "bar")
               .attr("x", function(d) { return xScale(d.label); })
               .attr("y", function(d) { return yScale(d.value); })
               .attr("width", xScale.bandwidth())
               .attr("height", function(d) { return height - yScale(d.value); })
               .style('fill','#899da6');
          }
          </script>
      </body>
  {% endif %}
  {% endblock js %}

clinic/templates/researcher/data_list.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'table' %}" class="btn btn-student btn-lg" role="button">Click here for Exercise list</a>
</br>
</br>
<body>

  <!-- start sw-rss-feed code -->
  <script type="text/javascript">
  <!--
  rssfeed_url = new Array();
  rssfeed_url[0]="https://www.sciencedaily.com/rss/health_medicine/parkinson's_disease.xml";
  rssfeed_frame_width="800";
  rssfeed_frame_height="900";
  rssfeed_scroll="on";
  rssfeed_scroll_step="6";
  rssfeed_scroll_bar="off";
  rssfeed_target="_blank";
  rssfeed_font_size="12";
  rssfeed_font_face="";
  rssfeed_border="on";
  rssfeed_css_url="https://feed.surfing-waves.com/css/style3a.css";
  rssfeed_title="on";
  rssfeed_title_name="";
  rssfeed_title_bgcolor="#3366ff";
  rssfeed_title_color="#fff";
  rssfeed_title_bgimage="";
  rssfeed_footer="off";
  rssfeed_footer_name="rss feed";
  rssfeed_footer_bgcolor="#fff";
  rssfeed_footer_color="#333";
  rssfeed_footer_bgimage="";
  rssfeed_item_title_length="50";
  rssfeed_item_title_color="#666";
  rssfeed_item_bgcolor="#fff";
  rssfeed_item_bgimage="";
  rssfeed_item_border_bottom="on";
  rssfeed_item_source_icon="off";
  rssfeed_item_date="off";
  rssfeed_item_description="on";
  rssfeed_item_description_length="120";
  rssfeed_item_description_color="#666";
  rssfeed_item_description_link_color="#333";
  rssfeed_item_description_tag="off";
  rssfeed_no_items="0";
  rssfeed_cache = "57346ef4c0b2ec4019cc6aaefcad2d84";
  //-->
  </script>
  <script type="text/javascript" src="//feed.surfing-waves.com/js/rss-feed.js"></script>
  <!-- The link below helps keep this service FREE, and helps other people find the SW widget. Please be cool and keep it! Thanks. -->
  <div style="color:#ccc;font-size:10px; text-align:right; width:800px;">powered by <a href="https://surfing-waves.com" rel="noopener" target="_blank" style="color:#ccc;">Surfing Waves</a></div>
  <!-- end sw-rss-feed code -->

</body>

<footer>
<a href="/hello"" class="btn btn-teacher btn-lg" role="button">Patient Location</a>
</footer>
<!--

  {% include 'clinic/students/_header.html' with active='new' %}
  <div class="card">
  <a href="/maps_loc"" class="btn btn-teacher btn-lg" role="button">view maps</a>
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Quiz</th>
          <th>Subject</th>
          <th>Length</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for quiz in quizzes %}
          <tr>
            <td class="align-middle">{{ quiz.name }}</td>
            <td class="align-middle">{{ quiz.subject.get_html_badge }}</td>
            <td class="align-middle">{{ quiz.questions_count }} questions</td>
            <td class="text-right">
              <a href="{% url 'students:take_quiz' quiz.pk %}" class="btn btn-primary">Start quiz</a>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="4">No quiz matching your interests right now.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div> -->
{% endblock %}

clinic/templates/researcher/graph_list.html
<!DOCTYPE html>
<meta charset="utf-8">
<style>

body {
  font: 10px sans-serif;
}

.axis path,
.axis line {
  fill: none;
  stroke: #000;
  shape-rendering: crispEdges;
}

.x.axis path {
  display: none;
}

.line {
  fill: none;
  stroke: steelblue;
  stroke-width: 1.5px;
}

</style>
<body>
<script src="http://d3js.org/d3.v3.js"></script>
<script>

var margin = {top: 20, right: 20, bottom: 30, left: 50},
    width = 960 - margin.left - margin.right,
    height = 500 - margin.top - margin.bottom;

var parseDate = d3.time.format("%Y-%m-%d").parse; // for dates like "2014-01-01"
//var parseDate = d3.time.format("%Y-%m-%dT00:00:00Z").parse;  // for dates like "2014-01-01T00:00:00Z"

var x = d3.time.scale()
    .range([0, width]);

var y = d3.scale.linear()
    .range([height, 0]);

var xAxis = d3.svg.axis()
    .scale(x)
    .orient("bottom");

var yAxis = d3.svg.axis()
    .scale(y)
    .orient("left");

var line = d3.svg.line()
    .x(function(d) { return x(d.month); })
    .y(function(d) { return y(d.count_items); });

var svg = d3.select("body").append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

d3.json("{% url "play_count_by_month" %}", function(error, data) {
  data.forEach(function(d) {
    d.month = parseDate(d.month);
    d.count_items = +d.count_items;
  });

  x.domain(d3.extent(data, function(d) { return d.month; }));
  y.domain(d3.extent(data, function(d) { return d.count_items; }));

  svg.append("g")
      .attr("class", "x axis")
      .attr("transform", "translate(0," + height + ")")
      .call(xAxis);

  svg.append("g")
      .attr("class", "y axis")
      .call(yAxis)
    .append("text")
      .attr("transform", "rotate(-90)")
      .attr("y", 6)
      .attr("dy", ".71em")
      .style("text-anchor", "end")
      .text("Play count");

  svg.append("path")
      .datum(data)
      .attr("class", "line")
      .attr("d", line);
});

</script>
</body>
</html>

clinic/templates/researcher/interests_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <!--<h2 class="mb-3">Update your interests</h2>-->
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Save changes</button>
    <a href="{% url 'students:quiz_list' %}" class="btn btn-outline-secondary">Nevermind</a>
  </form>
{% endblock %}